{
 "title": "devtestbr Metrics dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": " 5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container!=\"POD\"},namespace)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container_name!=\"POD\"},container_name)"
   }
  ]
 },
 "panels": [
  { "title": "K6 InfluxDB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "devtestbr Prometheus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Running Pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "HTTP Request Rate/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "rate(node_http_requests_total{status=\"200\"}[2m])",
     "legendFormat": "address: {{instance}}"
    }
   ]
  },
  {
   "title": "Response Time -  0.99 Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "node_http_duration_seconds{quantile=\"0.99\"} * 1000",
     "legendFormat": "address {{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (id,pod)",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Archived",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checks Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_check",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "check" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "checks",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total devtestbr Pods",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 6, "y": 26 },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{container=\"devtestbr\"})"
      }
     ]
    }
   ]
  }
 ]
}