apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtestbr-api
  labels:
    app: devtestbr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devtestbr-api
  template:
    metadata:
      labels:
        app: devtestbr-api
    spec:
      containers:
        - name: devtestbr
          image: brandiqa/devtestbr-api
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
---
kind: Service
apiVersion: v1
metadata:
  name: devtestbr-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4000"
    prometheus.io/path: "/metrics"
spec:
  type: LoadBalancer
  selector:
    app: devtestbr-api
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
